"""empty message

Revision ID: a223753e1a9f
Revises: 096f9ee63c6e
Create Date: 2024-06-23 03:38:29.131823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a223753e1a9f'
down_revision = '096f9ee63c6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paiements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('commande_id', sa.Integer(), nullable=False),
    sa.Column('montant', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('methode_paiement', sa.String(length=50), nullable=False),
    sa.Column('statut', sa.String(length=50), nullable=False),
    sa.Column('date_paiement', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['commande_id'], ['commandes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('commandes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adresse_livraison', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('telephone', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commandes', schema=None) as batch_op:
        batch_op.drop_column('telephone')
        batch_op.drop_column('adresse_livraison')

    op.drop_table('paiements')
    # ### end Alembic commands ###
